# Generated by Django 3.2.11 on 2022-01-19 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('title', models.CharField(max_length=128, verbose_name='Заголовок')),
                ('image', models.CharField(max_length=64, verbose_name='Картинка')),
                ('short_text', models.CharField(max_length=255, verbose_name='Краткое описание')),
                ('text', models.TextField(max_length=10000, verbose_name='Текст новости')),
            ],
            options={
                'verbose_name': 'Новости',
                'verbose_name_plural': 'Новости',
                'ordering': ('-created',),
            },
        ),
    ]
