# Generated by Django 3.2.10 on 2022-01-21 03:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания записи')),
                ('name', models.CharField(blank=True, db_index=True, max_length=255, verbose_name='Имя организации')),
                ('logo', models.FileField(blank=True, max_length=64, null=True, upload_to='', verbose_name='Логотип организации')),
                ('url', models.URLField(blank=True, max_length=64, null=True, verbose_name='Сайт компании')),
                ('city', models.CharField(blank=True, db_index=True, max_length=64, null=True, verbose_name='Город')),
                ('address', models.CharField(blank=True, max_length=64, null=True, verbose_name='Адрес организации')),
                ('description', models.TextField(blank=True, max_length=5000, null=True, verbose_name='Описание организации')),
                ('is_active', models.BooleanField(db_index=True, default=False, verbose_name='Активность')),
            ],
            options={
                'verbose_name': 'Организация',
                'verbose_name_plural': 'Организации',
            },
        ),
        migrations.CreateModel(
            name='CompanyModeration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, choices=[('Неизвестно', 'Неизвестно'), ('Подтверждено', 'Подтверждено'), ('Запрещено', 'Запрещено')], max_length=100, null=True, verbose_name='Статус')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий модератора')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Время отправления комментария')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.company')),
            ],
            options={
                'verbose_name': 'Модерация организаций ',
                'verbose_name_plural': 'Модерация организаций',
            },
        ),
    ]
