# Generated by Django 3.2.11 on 2022-01-08 13:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания записи')),
                ('name', models.CharField(db_index=True, max_length=255, verbose_name='Имя организации')),
                ('logo', models.FileField(max_length=64, null=True, upload_to='', verbose_name='Логотип организации')),
                ('url', models.FileField(max_length=64, null=True, upload_to='', verbose_name='Сайт компании')),
                ('city', models.CharField(db_index=True, max_length=64, null=True, verbose_name='Город')),
                ('address', models.CharField(max_length=64, null=True, verbose_name='Адрес организации')),
                ('description', models.TextField(null=True, verbose_name='Описание организации')),
                ('is_active', models.BooleanField(db_index=True, default=False, verbose_name='Активность')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Company - Организации',
            },
        ),
    ]
