# Generated by Django 3.2.11 on 2022-01-19 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_company_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyModeration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Статус неопределенный'), (1, 'Подтверждено'), (2, 'Запрещено')], null=True, verbose_name='Статус')),
                ('comment', models.TextField(blank=True, verbose_name='Комментрарий модератора')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Время отпраления комментария')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.company')),
            ],
        ),
    ]
