# Generated by Django 3.2.11 on 2022-01-19 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_companymoderation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companymoderation',
            name='status',
            field=models.CharField(blank=True, choices=[('Статус неопределенный', 'Статус неопределенный'), ('Подтверждено', 'Подтверждено'), ('Запрещено', 'Запрещено')], max_length=100, null=True, verbose_name='Статус'),
        ),
    ]
