# Generated by Django 3.2.11 on 2022-01-19 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0004_alter_companymoderation_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='companymoderation',
            options={'verbose_name': 'Модерация организаций ', 'verbose_name_plural': 'Модерация организаций'},
        ),
    ]
