# Generated by Django 3.2.11 on 2022-01-20 17:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skills', models.CharField(blank=True, max_length=500, verbose_name='навыки')),
                ('birthday', models.DateField(blank=True, default='1900-01-01', verbose_name='дата рождения')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='город')),
                ('aboutMe', models.TextField(blank=True, max_length=5000, verbose_name='о себе')),
                ('gender', models.CharField(blank=True, choices=[('M', 'М'), ('W', 'Ж')], max_length=1, verbose_name='пол')),
                ('avatar', models.FileField(blank=True, max_length=64, null=True, upload_to='', verbose_name='Фотография')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
