# Generated by Django 3.2.11 on 2022-01-04 21:34

from django.db import migrations


def generate_default_users(apps, schema_editor):
    User = apps.get_model('users', 'User')
    User.objects.create_user(
        username='moderator@mail.ru',
        last_name='Модератор',
        first_name='Иван',
        second_name='Иванович',
        phone='+7(900)000-00-01',
        role=1,  # User.USER_TYPE_MODERATOR,
        password='1',
        is_staff=True,
        is_superuser=True,
    )
    User.objects.create_user(
        username='employee@mail.ru',
        last_name='Сотрудник',
        first_name='Иван',
        second_name='Иванович',
        phone='+7(900)000-00-02',
        role=2,  # User.USER_TYPE_EMPLOYEE,
        password='1',
    )
    User.objects.create_user(
        username='employer@mail.ru',
        last_name='Работодатель',
        first_name='Иван',
        second_name='Иванович',
        phone='+7(900)000-00-03',
        role=3,  # User.USER_TYPE_EMPLOYER,
        password='1',
    )


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(generate_default_users, reverse_code=migrations.RunPython.noop),
    ]
