# Generated by Django 3.2.11 on 2022-01-19 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeprofile',
            name='birthday',
            field=models.DateField(blank=True, default='1900-01-01'),
        ),
    ]
