# Generated by Django 3.2.11 on 2022-01-20 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_employeeprofile_birthday'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeeprofile',
            name='tagline',
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='city',
            field=models.CharField(blank=True, max_length=100, verbose_name='город'),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='skills',
            field=models.CharField(blank=True, max_length=500, verbose_name='навыки'),
        ),
        migrations.AlterField(
            model_name='employeeprofile',
            name='birthday',
            field=models.DateField(blank=True, default='1900-01-01', verbose_name='дата рождения'),
        ),
    ]
