# Generated by Django 3.2.11 on 2022-01-20 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20220120_0812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeprofile',
            name='avatar',
            field=models.FileField(blank=True, max_length=64, null=True, upload_to='', verbose_name='Фотография'),
        ),
    ]
