# Generated by Django 3.2.11 on 2022-01-18 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('educational_institution', models.CharField(max_length=255, verbose_name='Учебное заведение')),
                ('faculty', models.CharField(max_length=255, verbose_name='Факультет')),
                ('specialization', models.CharField(blank=True, max_length=255, null=True, verbose_name='Специализация')),
                ('year_of_ending', models.IntegerField(verbose_name='Год окончания')),
            ],
            options={
                'verbose_name': 'Курс',
                'verbose_name_plural': 'Повышение квалификации, курсы',
            },
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Среднее специальное'), (2, 'Неоконченное высшее'), (3, 'Высшее'), (4, 'Бакалавр'), (5, 'Магистр'), (6, 'Кандидат наук'), (7, 'Доктор наук')], null=True, verbose_name='Уровень')),
                ('educational_institution', models.CharField(max_length=255, verbose_name='Учебное заведение')),
                ('faculty', models.CharField(max_length=255, verbose_name='Факультет')),
                ('specialization', models.CharField(blank=True, max_length=255, null=True, verbose_name='Специализация')),
                ('year_of_ending', models.IntegerField(verbose_name='Год окончания')),
            ],
            options={
                'verbose_name': 'Образование',
                'verbose_name_plural': 'Образование',
                'ordering': ('-year_of_ending',),
            },
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Начало работы')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Окончание')),
                ('organization_name', models.CharField(max_length=128, verbose_name='Организация')),
                ('position', models.CharField(max_length=128, verbose_name='Должность')),
                ('duties', models.TextField(max_length=255, verbose_name='Обязанности на рабочем месте')),
            ],
            options={
                'verbose_name': 'Опыт работы',
                'verbose_name_plural': 'Опыт работы',
                'ordering': ('-start_date', '-end_date'),
            },
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменен')),
                ('name', models.CharField(db_index=True, max_length=128, verbose_name='Название резюме')),
                ('price', models.IntegerField(blank=True, db_index=True, null=True, verbose_name='Зарплата')),
                ('about_me', models.TextField(blank=True, max_length=500, null=True, verbose_name='Обо мне')),
                ('is_draft', models.BooleanField(db_index=True, default=True, verbose_name='Черновик')),
                ('is_active', models.BooleanField(db_index=True, default=False, verbose_name='Активен')),
                ('courses', models.ManyToManyField(blank=True, db_index=True, to='resume.Courses', verbose_name='Курсы')),
                ('education', models.ManyToManyField(blank=True, db_index=True, to='resume.Education', verbose_name='Образование')),
                ('experience', models.ManyToManyField(blank=True, db_index=True, to='resume.Experience', verbose_name='Опыт работы')),
            ],
            options={
                'verbose_name': 'Резюме',
                'verbose_name_plural': 'Резюме',
            },
        ),
        migrations.CreateModel(
            name='ResumeSkills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=32, verbose_name='Навык')),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume.resume', verbose_name='Резюме')),
            ],
            options={
                'verbose_name': 'Ключевой навык',
                'verbose_name_plural': 'Ключевые навыки вакансии',
            },
        ),
    ]
