# Generated by Django 3.2.11 on 2022-01-19 21:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0002_resume_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResumeModeration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, choices=[('Статус неопределенный', 'Статус неопределенный'), ('Подтверждено', 'Подтверждено'), ('Запрещено', 'Запрещено')], max_length=100, null=True, verbose_name='Статус')),
                ('comment', models.TextField(blank=True, verbose_name='Комментрарий модератора')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Время отпраления комментария')),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume.resume')),
            ],
            options={
                'verbose_name': 'Модерация резюме ',
                'verbose_name_plural': 'Модерация резюме',
            },
        ),
    ]
