# Generated by Django 3.2.10 on 2022-01-29 03:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SMTPAccount",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("host", models.CharField(default="smtp.yandex.ru", max_length=255, verbose_name="Хост")),
                ("port", models.IntegerField(default=587, verbose_name="Порт")),
                ("is_use_tls", models.BooleanField(default=True, verbose_name="Использовать TLS?")),
                ("is_use_ssl", models.BooleanField(default=False, verbose_name="Использовать SSL?")),
                ("sender", models.EmailField(blank=True, default="", max_length=255, verbose_name="Отправитель")),
                ("username", models.CharField(blank=True, default="", max_length=255, verbose_name="Имя пользователя")),
                (
                    "password",
                    models.CharField(blank=True, default="", max_length=255, verbose_name="Пароль пользователя"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Включить аккаунт")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Дата создания")),
            ],
            options={"verbose_name": "SMTP аккаунт", "verbose_name_plural": "SMTP аккаунты",},
        ),
        migrations.CreateModel(
            name="NotifyTemplate",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=255, verbose_name="Название для админа")),
                ("subject", models.CharField(blank=True, default="", max_length=255, verbose_name="Заголовок")),
                ("text", models.TextField(verbose_name="Текст")),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        help_text="Используется только в случае отсутствия указанного пользователя",
                        max_length=255,
                        null=True,
                        verbose_name="Email получатель",
                    ),
                ),
                ("type", models.IntegerField(choices=[(0, "E-mail"), (1, "Message")], verbose_name="Тип")),
                (
                    "event",
                    models.IntegerField(
                        blank=True,
                        choices=[(1, "Register"), (2, "Feeback"), (3, "Message")],
                        null=True,
                        verbose_name="Событие",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Дата создания")),
                ("is_active", models.BooleanField(default=True, verbose_name="Активный")),
                ("send_at", models.DateTimeField(blank=True, null=True, verbose_name="Время начала отправки")),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь (получатель)",
                    ),
                ),
            ],
            options={"verbose_name": "Шаблон", "verbose_name_plural": "Шаблоны",},
        ),
        migrations.CreateModel(
            name="Notify",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("subject", models.CharField(blank=True, default="", max_length=255, verbose_name="Тема")),
                ("text", models.TextField(verbose_name="Текст")),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        help_text="Используется только в случае отсутствия указанного пользователя",
                        max_length=255,
                        null=True,
                        verbose_name="Email Получателя",
                    ),
                ),
                (
                    "sender_email",
                    models.EmailField(blank=True, max_length=255, null=True, verbose_name="Email Отправителя"),
                ),
                ("type", models.IntegerField(choices=[(0, "E-mail"), (1, "Message")], verbose_name="Тип")),
                ("is_read", models.BooleanField(default=False, verbose_name="Прочитано")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Дата создания")),
                ("send_at", models.DateTimeField(blank=True, null=True, verbose_name="Время начала отправки")),
                ("sent_at", models.DateTimeField(blank=True, null=True, verbose_name="Дата отправки")),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="notifies",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь (получатель)",
                    ),
                ),
            ],
            options={"verbose_name": "Уведомление", "verbose_name_plural": "Уведомления",},
        ),
    ]
